# kubesphere configuration

server:
  http:
    hostname: localhost
    port: 8000
    static:
      development:
        /public: server/public
        /assets: src/assets
        /build: build
        /dist: dist
      production:
        /public: server/public
        /assets: dist/assets
        /dist: dist
  db:
    host: dev.toimc.com
    port: 43005
    user: root
    password: 9igAUTJVnBwBQPpn
    db: res_platform

  # redis config for multi replicas
  # redis:
  #   port: 6379
  #   host: 127.0.0.1
  redisTimeout: 5000

  # kubesphere console session params, not login session
  sessionKey: "kubesphere:sess"
  sessionTimeout: 3600000 # unit: millisecond

  # backend service gateway server
  apiServer:
    url: http://test.bontor.cn:30881
    wsUrl: ws://test.bontor.cn:30881

  # docker image search default url
  dockerHubUrl: https://hub.docker.com

client:
  title: "网进AI基础资源管理平台"
  description: ""
  logo: "/assets/base/logo2.png"

  version:
    kubesphere: 3.1.0

  # kubesphere urls
  issueUrl: https://github.com/kubesphere/kubesphere/issues/new/choose
  reposUrl: https://github.com/kubesphere/kubesphere
  slackUrl: https://kubesphere.slack.com
  documents:
    url: https://v3-1.docs.kubesphere.io/docs
    api: https://v3-1.docs.kubesphere.io/docs/reference/api-docs/

  # current support lanaguages
  supportLangs:
    - label: "繁體中文"
      value: "tc"
    - label: "简体中文"
      value: "zh"
    - label: "English"
      value: "en"
    - label: "Español"
      value: "es"
  defaultLang: "en"

  # access control page navigations
  accessNavs:
    - cate: "access"
      items:
        - { name: workspaces, title: Workspaces, icon: enterprise }
        - { name: accounts, title: NAV_ACCOUNTS, icon: human, authKey: users }
        - { name: roles, title: Account Roles, icon: role }

  # platform settings navigations
  platformSettingsNavs:
    - cate: "platformsettings"
      items:
        - {
            name: base-info,
            title: Platform Info,
            icon: home,
            authKey: platform-settings,
          }
        - name: notification-management
          title: Notification Management
          icon: bell
          children:
            - { name: mail, title: Mail, authKey: platform-settings }
            - { name: dingtalk, title: DingTalk, authKey: platform-settings }
            - { name: wecom, title: WeCom, authKey: platform-settings }
            - { name: slack, title: Slack, authKey: platform-settings }
            - { name: webhook, title: Webhook, authKey: platform-settings }

  # apps manage page navigations
  manageAppNavs:
    - cate: "apps"
      items:
        - { name: store, title: App Store, icon: appcenter }
        - { name: categories, title: App Categories, icon: tag }
        - { name: reviews, title: App Review, icon: safe-notice }

  # project page navigations
  projectNavs:
    - cate: "project"
      items:
        - {
            name: overview,
            title: Overview,
            icon: HomeOutlined,
            authKey: "services",
          }
        - name: app-workloads
          title: DockerManageMent
          icon: AppstoreAddOutlined
          children:
            - { name: template, title: AppTemplate, icon: application }
            - { name: apply, title: ApplyResource, icon: application }
            - { name: audit, title: AppApproval, icon: application }
            - { name: applications, title: Applications, icon: application }
            - { name: services, title: DockerService }
            - { name: pods, title: Pods }
        # - { name: services, title: Services }
        # - name: workloads
        #   title: Workloads
        #   tabs:
        #     - { name: deployments, title: Deployments }
        #     - { name: statefulsets, title: StatefulSets }
        #     - { name: daemonsets, title: DaemonSets }
        # 容器智能调度
        - name: workloads
          title: Workloads
          icon: ClusterOutlined
          children:
            - name: workloads
              title: LifeCircle
              tabs:
                - { name: deployments, title: Deployments }
                - { name: statefulsets, title: StatefulSets }
                - { name: daemonsets, title: DaemonSets }
            - {
                # 这里的name对应路由的路径
                name: devops/default5tmqc,
                title: DevOps Projects,
                icon: strategy-group,
                ksModule: devops,
                skipAuth: true,
              }
            - {
                name: "gitlab",
                title: Gitlab,
                link: "http://test.bontor.cn:30000/",
              }
            - {
                name: s2ibuilders,
                title: Image Builder,
                icon: vnas,
                clusterModule: devops,
              }
        - name: storage
          title: Storage Management
          icon: HddOutlined
          children:
            - { name: volumes, title: Volumes }
            - { name: volume-snapshots, title: Snapshots }
        - name: config
          title: Configuration Center
          icon: ToolOutlined
          children:
            - { name: secrets, title: Secrets }
            - { name: configmaps, title: ConfigMaps }
            # - {
            #     name: serviceaccounts,
            #     title: ServiceAccounts,
            #     requiredClusterVersion: v3.1.0,
            #   }
        - {
            name: grayrelease,
            title: Grayscale Release,
            icon: bird,
            authKey: grayscale-release,
            clusterModule: servicemesh,
          }
        - name: monitoring
          title: Monitoring & Alerting
          icon: DashboardOutlined
          children:
            - {
                name: alerts,
                title: Alerting Messages,
                icon: loudspeaker,
                clusterModule: alerting,
                requiredClusterVersion: v3.1.0,
              }
            - {
                name: alert-rules,
                title: Alerting Policies,
                icon: hammer,
                clusterModule: alerting,
                requiredClusterVersion: v3.1.0,
              }
            - {
                name: custom-monitoring,
                title: Custom Monitoring,
                requiredClusterVersion: v3.1.0,
              }
        - name: project-settings
          title: Project Settings
          icon: SettingOutlined
          children:
            - { name: base-info, title: Basic Info, skipAuth: true }
            - {
                name: networkpolicies,
                title: Network Isolation,
                clusterModule: network,
                authKey: "project-settings",
              }
            - { name: roles, title: Project Roles }
            - { name: members, title: Project Members }
            # - {
            #     name: advanced,
            #     title: Advanced Settings,
            #     authKey: "project-settings",
            #   }

  # federatedProjectNavs:
  #   - cate: "project"
  #     items:
  #       - { name: overview, title: Overview, icon: dashboard, skipAuth: true }
  #       - name: app-workloads
  #         title: Application Workloads
  #         icon: appcenter
  #         children:
  #           - { name: applications, title: Applications, icon: application }
  #           - { name: services, title: Services }
  #           - name: workloads
  #             title: Workloads
  #             tabs:
  #               - { name: deployments, title: Deployments }
  #               - { name: statefulsets, title: StatefulSets }
  #           - { name: ingresses, title: Routes }
  #       - { name: volumes, title: Volumes, icon: storage }
  #       - name: config
  #         title: Configuration Center
  #         icon: hammer
  #         children:
  #           - { name: secrets, title: Secrets }
  #           - { name: configmaps, title: ConfigMaps }
  #       - name: settings
  #         title: Project Settings
  #         icon: cogwheel
  #         children:
  #           - { name: base-info, title: Basic Info, skipAuth: true }
  #           - {
  #               name: quota,
  #               title: Quota Management,
  #               authKey: "project-settings",
  #             }
  #           - {
  #               name: advanced,
  #               title: Advanced Settings,
  #               authKey: "project-settings",
  #             }

  # devops page navigations
  devopsNavs:
    - cate: ""
      items:
        - { name: pipelines, title: Pipelines, icon: application }
        - { name: credentials, title: Credentials, icon: cogwheel }
        # - name: management
        #   title: DEVOPS_PROJECT_MANAGEMENT
        #   icon: cogwheel
        #   open: true
        #   children:
        # - { name: base-info, title: Basic Info, skipAuth: true }
        # - { name: credentials, title: Credentials }
        # - { name: roles, title: DEVOPS_PROJECT_ROLES }
        # - { name: members, title: DEVOPS_PROJECT_MEMBERS }

  # system workspace rules control
  systemWorkspace: system-workspace
  systemWorkspaceRules:
    devops: []
    members: [manage]
    projects: [view, edit, manage]
    roles: [view]
    workspaces: [view, edit]
  systemWorkspaceProjectRules:
    alerting: [manage]
    members: [manage]
    roles: [manage]
    custom-monitoring: [manage]

  # preset infos
  presetUsers: [admin, sonarqube]
  presetGlobalRoles:
    [platform-admin, platform-regular, workspaces-manager, users-manager]
  presetClusterRoles: [cluster-admin, cluster-viewer]
  presetWorkspaceRoles: [admin, regular, viewer, self-provisioner]
  presetDevOpsRoles: [admin, operator, viewer]
  presetRoles: [admin, operator, viewer]

  # system annotations that need to be hidden for edit
  preservedAnnotations: [".*kubesphere.io/", "openpitrix_runtime"]

  # namespaces that need to be disable collection file log
  disabledLoggingSidecarNamespace: ["kubesphere-logging-system"]

  # loadbalancer annotations, default support qingcloud lb
  loadBalancerDefaultAnnotations:
    service.beta.kubernetes.io/qingcloud-load-balancer-eip-ids: ""
    service.beta.kubernetes.io/qingcloud-load-balancer-type: "0"

  # control error notify on page
  enableErrorNotify: true

  # enable image search when add image for a container
  enableImageSearch: true

  # development
  # disable authorization check when developing
  disableAuthorization: false

  # show kubeconfig
  enableKubeConfig: true

  # third party tools
  thirdPartyTools:
    []
    # - title:
    #   description:
    #   link:

  # docs url for resources
  resourceDocs:
    # Project User Guide
    applications: /project-user-guide/application/app-template/
    composingapps: /project-user-guide/application/compose-app/
    deployments: /project-user-guide/application-workloads/deployments/
    statefulsets: /project-user-guide/application-workloads/statefulsets/
    daemonsets: /project-user-guide/application-workloads/daemonsets/
    jobs: /project-user-guide/application-workloads/jobs/
    cronjobs: /project-user-guide/application-workloads/cronjobs/
    services: /project-user-guide/application-workloads/services/
    ingresses: /project-user-guide/application-workloads/routes/
    s2i_template: /project-user-guide/image-builder/s2i-templates/
    volumes: /project-user-guide/storage/volumes/
    secrets: /project-user-guide/configuration/secrets/
    configmaps: /project-user-guide/configuration/configmaps/
    serviceaccounts: /project-user-guide/configuration/serviceaccounts/
    imageregistry: /project-user-guide/configuration/image-registry/
    grayrelease: /project-user-guide/grayscale-release/overview/

    # Project Administration
    internet: /project-administration/project-gateway/
    project_base_info: /workspace-administration/project-quotas/
    project_roles: /project-administration/role-and-member-management/
    project_members: /project-administration/role-and-member-management/

    # Cluster Administrator Guide
    nodes: /cluster-administration/nodes/
    storageclasses: /cluster-administration/persistent-volume-and-storage-class/

    # DevOps User Guide
    pipelines: /devops-user-guide/how-to-use/pipeline-settings/
    cridentials: /devops-user-guide/how-to-use/credential-management/

    # Developer Guide
    helm_specification: /application-store/app-developer-guide/helm-specification/
    helm_developer_guide: /application-store/app-developer-guide/helm-developer-guide/

    # Custom Console
    custom_console: /cluster-administration/platform-settings/customize-basic-information/

    # Kube Config
    kube_config: /multicluster-management/enable-multicluster/retrieve-kubeconfig/
  # devops:
  #  replace sonarqube link to customize url origin, default is useless
  # sonarqubeURL: http://139.123.123.123:8080

  #notification management
  notification:
    mail:
      max_number_of_eamil: 50
    dingtalk:
      max_number_of_cid: 20
      max_number_of_keyword: 20
    wecom:
      max_number_of_toUser: 50
      max_number_of_toParty: 20
      max_number_of_toTag: 20
    slack:
      max_number_of_channel: 20
