// 企业空间权限
export const SPACE_ROLES = [
  'role-template-create-devops',
  'role-template-create-projects',
  'role-template-manage-projects',
  'role-template-view-projects',
  'role-template-view-members',
  'role-template-manage-devops',
  'role-template-view-devops',
  'role-template-manage-app-repos',
  'role-template-view-app-repos',
  'role-template-manage-app-templates',
  'role-template-view-app-templates',
  'role-template-manage-groups',
  'role-template-view-groups',
  'role-template-view-roles',
  'role-template-manage-members',
  'role-template-manage-roles',
  'role-template-manage-workspace-settings',
  'role-template-view-workspace-settings',
  'role-template-view-basic',
]

export const PROJECT_ROLES = [
  'role-template-view-app-workloads',
  'role-template-view-volumes',
  'role-template-view-secrets',
  'role-template-view-configmaps',
  'role-template-view-snapshots',
  'role-template-manage-snapshots',
  'role-template-manage-volumes',
  'role-template-manage-configmaps',
  'role-template-manage-serviceaccount',
  'role-template-view-serviceaccount',
  'role-template-view-roles',
  'role-template-view-members',
  'role-template-manage-alerting-messages',
  'role-template-view-alerting-messages',
  'role-template-manage-alerting-policies',
  'role-template-view-alerting-policies',
  'role-template-manage-custom-monitoring',
  'role-template-view-custom-monitoring',
  'role-template-manage-members',
  'role-template-manage-roles',
  'role-template-manage-project-settings',
  'role-template-view-basic',
  'role-template-manage-app-workloads',
  'role-template-manage-secrets',
]

// 企业空间所有的权限
export const SPACE_RULES = [
  {
    verbs: ['create', 'watch'],
    apiGroups: ['*'],
    resources: ['devops', 'devopsprojects'],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: ['*'],
    resources: [
      'workspaces',
      'workspacemembers',
      'quotas',
      'abnormalworkloads',
      'pods',
    ],
  },
  {
    verbs: ['create', 'watch'],
    apiGroups: ['*'],
    resources: ['namespaces', 'federatednamespaces'],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: ['*'],
    resources: ['workspacemembers'],
  },
  {
    verbs: ['*'],
    apiGroups: ['*'],
    resources: [
      'pipelines',
      'pipelines/runs',
      'pipelines/branches',
      'pipelines/checkScriptCompile',
      'pipelines/consolelog',
      'pipelines/scan',
      'pipelines/sonarstatus',
      'checkCron',
      'credentials',
      'credentials/usage',
      'roles',
      'members',
      'devops',
      'devopsprojects',
    ],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: ['*'],
    resources: [
      'pipelines',
      'pipelines/runs',
      'pipelines/branches',
      'pipelines/checkScriptCompile',
      'pipelines/consolelog',
      'pipelines/scan',
      'pipelines/sonarstatus',
      'checkCron',
      'credentials',
      'credentials/usage',
      'roles',
      'members',
      'devops',
      'devopsprojects',
    ],
  },
  {
    verbs: ['*'],
    apiGroups: ['openpitrix.io'],
    resources: ['repos', 'repos/events', 'repos/action'],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: ['openpitrix.io'],
    resources: ['repos', 'repos/events'],
  },
  {
    verbs: ['*'],
    apiGroups: ['openpitrix.io'],
    resources: ['*'],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: ['openpitrix.io'],
    resources: ['*'],
  },
  {
    verbs: ['*'],
    apiGroups: ['*'],
    resources: [
      'groups',
      'groupbindings',
      'rolebindings',
      'workspacerolebindings',
    ],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: ['*'],
    resources: [
      'groups',
      'groupbindings',
      'roles',
      'rolebindings',
      'workspacerolebindings',
      'namespaces',
    ],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: ['*'],
    resources: ['workspaceroles'],
  },
  {
    verbs: ['*'],
    apiGroups: ['*'],
    resources: ['workspacemembers'],
  },
  {
    verbs: ['list', 'get', 'watch'],
    apiGroups: ['*'],
    resources: ['workspaceroles'],
  },
  {
    verbs: ['*'],
    apiGroups: ['*'],
    resources: ['workspaceroles'],
  },
  {
    verbs: ['*'],
    apiGroups: ['*'],
    resources: ['workspaces'],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: ['*'],
    resources: ['workspaces'],
  },
  {
    verbs: ['get'],
    apiGroups: ['*'],
    resources: ['workspaces'],
  },
  {
    verbs: ['get', 'list'],
    apiGroups: [
      'monitoring.kubesphere.io',
      'metering.kubesphere.io',
      'monitoring.coreos.com',
    ],
    resources: ['namespaces', 'workloads'],
  },
  {
    verbs: ['watch'],
    apiGroups: ['*'],
    resources: ['namespaces'],
  },
  {
    verbs: ['list'],
    apiGroups: ['iam.kubesphere.io'],
    resources: ['workspacemembers'],
  },
]

export const PROJECT_RULES = [
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: [
      'monitoring.kubesphere.io',
      'metering.kubesphere.io',
      'monitoring.coreos.com',
      'servicemesh.kubesphere.io',
    ],
    resources: ['*'],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: ['*'],
    resources: [
      'services',
      'applications',
      'controllerrevisions',
      'deployments',
      'replicasets',
      'statefulsets',
      'daemonsets',
      'jobs',
      'cronjobs',
      'pods',
      'pods/log',
      'pods/containers',
      'services',
      'ingresses',
      'router',
      's2ibinaries',
      's2ibinaries/file',
      's2ibuilders',
      's2ibuildertemplates',
      's2iruns',
      'horizontalpodautoscalers',
    ],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: ['*'],
    resources: ['persistentvolumeclaims'],
  },
  {
    verbs: ['list'],
    apiGroups: ['*'],
    resources: ['pods'],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: ['*'],
    resources: ['secrets'],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: ['*'],
    resources: ['configmaps'],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: ['*'],
    resources: ['volumesnapshots'],
  },
  {
    verbs: ['*'],
    apiGroups: ['*'],
    resources: ['volumesnapshots'],
  },
  {
    verbs: ['*'],
    apiGroups: ['*'],
    resources: ['persistentvolumeclaims'],
  },
  {
    verbs: ['list'],
    apiGroups: ['*'],
    resources: ['pods'],
  },
  {
    verbs: ['*'],
    apiGroups: ['*'],
    resources: ['configmaps'],
  },
  {
    verbs: ['*'],
    apiGroups: ['*'],
    resources: ['serviceaccounts'],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: ['*'],
    resources: ['serviceaccounts'],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: ['*'],
    resources: ['roles'],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: ['*'],
    resources: ['members', 'rolebindings'],
  },
  {
    verbs: ['*'],
    apiGroups: ['alerting.kubesphere.io'],
    resources: ['*'],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: ['alerting.kubesphere.io'],
    resources: ['*'],
  },
  {
    verbs: ['*'],
    apiGroups: ['alerting.kubesphere.io'],
    resources: ['*'],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: ['alerting.kubesphere.io'],
    resources: ['*'],
  },
  {
    verbs: ['list'],
    apiGroups: ['resources.kubesphere.io'],
    resources: ['*'],
  },
  {
    verbs: ['*'],
    apiGroups: [
      'monitoring.kubesphere.io',
      'metering.kubesphere.io',
      'monitoring.coreos.com',
    ],
    resources: ['*'],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: [
      'monitoring.kubesphere.io',
      'metering.kubesphere.io',
      'monitoring.coreos.com',
    ],
    resources: ['*'],
  },
  {
    verbs: ['*'],
    apiGroups: ['*'],
    resources: ['members', 'rolebindings'],
  },
  {
    verbs: ['*'],
    apiGroups: ['*'],
    resources: ['roles'],
  },
  {
    verbs: ['*'],
    apiGroups: ['*'],
    resources: ['*'],
  },
  {
    verbs: ['get', 'list', 'watch'],
    apiGroups: ['*'],
    resources: [
      'namespaces',
      'quotas',
      'abnormalworkloads',
      'workloads',
      'limitranges',
      'events',
    ],
  },
]
